import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import meRouter from "./me";
import companiesRouter from "./companies";
import accountsRouter from "./accounts";
import periodsRouter from "./periods";
import journalEntriesRouter from "./journalEntries";
import ledgerRouter from "./ledger";
import counterpartiesRouter from "./counterparties";
import invoicesRouter from "./invoices";
import paymentsRouter from "./payments";
import vatCodesRouter from "./vatCodes";
import vatRegisterRouter from "./vatRegister";
import documentsRouter from "./documents";
import storageRouter from "./storage";
import bankStatementsRouter from "./bankStatements";
import dimensionsRouter from "./dimensions";
import reportsRouter from "./reports";
import importConfigRouter from "./importConfig";
import posRouter from "./pos/index";
import adminRouter from "./admin";
import superadminRouter from "./superadmin";
import ujpRouter from "./ujp";
import ajpesRouter from "./ajpes";
import posBookingSettingsRouter from "./posBookingSettings";
import vatLedgerReportRouter from "./vatLedgerReport";
import vatSubmissionsRouter from "./vatSubmissions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(companiesRouter);
router.use(accountsRouter);
router.use(periodsRouter);
router.use(journalEntriesRouter);
router.use(ledgerRouter);
router.use(counterpartiesRouter);
router.use(invoicesRouter);
router.use(paymentsRouter);
router.use(vatCodesRouter);
router.use(vatRegisterRouter);
router.use(documentsRouter);
router.use(storageRouter);
router.use(bankStatementsRouter);
router.use(dimensionsRouter);
router.use(reportsRouter);
router.use(importConfigRouter);
router.use("/admin", adminRouter);
router.use(superadminRouter);
router.use(ujpRouter);
router.use(ajpesRouter);
router.use(posBookingSettingsRouter);
router.use(vatLedgerReportRouter);
router.use(vatSubmissionsRouter);
router.use(posRouter);

export default router;
